# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\"\xc6\x04\n\x0cKspTelemetry\x12\x0b\n\x03sas\x18\x01 \x01(\x08\x12\x0b\n\x03rcs\x18\x02 \x01(\x08\x12\x10\n\x08\x63om_link\x18\x03 \x01(\x08\x12\x14\n\x0clanding_gear\x18\x04 \x01(\x08\x12\x0e\n\x06\x62rakes\x18\x05 \x01(\x08\x12\x0e\n\x06lights\x18\x06 \x01(\x08\x12\x10\n\x08grounded\x18\x07 \x01(\x08\x12\x13\n\x0b\x61lt_terrain\x18\x08 \x01(\x01\x12\x15\n\ralt_sea_level\x18\t \x01(\x01\x12\x10\n\x08\x61poapsis\x18\n \x01(\x01\x12\x11\n\tperiapsis\x18\x0b \x01(\x01\x12\x13\n\x0binclination\x18\x0c \x01(\x02\x12\x0e\n\x06\x65ta_pe\x18\r \x01(\x02\x12\x0e\n\x06\x65ta_ap\x18\x0e \x01(\x02\x12\x13\n\x0bvel_surface\x18\x0f \x01(\x02\x12\x11\n\tvel_orbit\x18\x10 \x01(\x02\x12\x12\n\nvel_target\x18\x11 \x01(\x02\x12\x17\n\x0fvel_h_component\x18\x12 \x01(\x02\x12\x17\n\x0fvel_v_component\x18\x13 \x01(\x02\x12\x0b\n\x03twr\x18\x14 \x01(\x02\x12\x19\n\x11kerbals_in_vessel\x18\x15 \x01(\x05\x12\x0f\n\x07g_force\x18\x16 \x01(\x02\x12\x14\n\x0ctime_elapsed\x18\x17 \x01(\x02\x12\x17\n\x0f\x65lectric_charge\x18\x18 \x01(\x02\x12\x10\n\x08monoprop\x18\x19 \x01(\x02\x12\x10\n\x08oxidizer\x18\x1a \x01(\x02\x12\x13\n\x0bliquid_fuel\x18\x1b \x01(\x02\x12\x16\n\x0e\x63urrent_planet\x18\x1c \x01(\t\x12\x15\n\rcurrent_stage\x18\x1d \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KSPTELEMETRY']._serialized_start=20
  _globals['_KSPTELEMETRY']._serialized_end=602
# @@protoc_insertion_point(module_scope)
